### ISSUE TITLE
create a postgres db when creating app

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/create-dogstack-app#11]
at the moment, no database is created when the app is generated - find a way to either do this automatically or alert the user they need to do it

**Comment by danalexilewis** [comment]
vote to tell the user to do it :)

**Comment by iainkirkpatrick** [comment]
addressed in [this PR](https://github.com/root-systems/create-dogstack-app/pull/12), wasn't hard to do automatically :) but will need better error handling around it i suspect. gonna open an issue for that
